// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxzpjfqdxpeyksfmjqii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4enBqZnFkeHBleWtzZm1qcWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDA5MjMsImV4cCI6MjA1Nzc3NjkyM30.B1U-PZY8fsnQ1AZX-kSwFoBaDKBkBK77xi1PN1sCsdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);